#include "native/embedded_assets.hpp"

#include <catch2/catch_test_macros.hpp>

using namespace mdview::assets;

TEST_CASE("embedded asset table is non-empty",
          "[embedded_assets]") {
    // Generated by GenerateViewerResources.cmake; should always
    // contain at least index.html, app.js, app.css.
    REQUIRE(!table().empty());
}

TEST_CASE("embedded asset table is sorted by path",
          "[embedded_assets]") {
    const auto t = table();
    for (std::size_t i = 1; i < t.size(); ++i) {
        CAPTURE(t[i - 1].path);
        CAPTURE(t[i].path);
        CHECK(t[i - 1].path < t[i].path);
    }
}

TEST_CASE("every entry has non-empty path and content_type",
          "[embedded_assets]") {
    for (const auto& a : table()) {
        CAPTURE(a.path);
        CHECK(!a.path.empty());
        CHECK(a.path.front() == L'/');
        CHECK(!a.content_type.empty());
        CHECK(a.resource_id >= 2000);
    }
}

TEST_CASE("find_asset locates /index.html",
          "[embedded_assets]") {
    REQUIRE(find_asset(L"/index.html") != nullptr);
}

TEST_CASE("find_asset locates /dist/app.js",
          "[embedded_assets]") {
    // Generated viewer paths are dist-rooted because index.html
    // references "dist/app.js" / "dist/app.css".
    REQUIRE(find_asset(L"/dist/app.js") != nullptr);
}

TEST_CASE("find_asset returns nullptr for unknown path",
          "[embedded_assets]") {
    CHECK(find_asset(L"/nope.txt") == nullptr);
    CHECK(find_asset(L"") == nullptr);
    CHECK(find_asset(L"/INDEX.HTML") == nullptr);  // case-sensitive
}
