# cmake/GenerateViewerResources.cmake
#
# Script-mode CMake that emits two artifacts from viewer/dist:
#   * ${OUTPUT_RC}  - Windows resource script. One RCDATA entry per
#                     embedded asset; resource IDs start at 2000.
#   * ${OUTPUT_CPP} - C++ source defining the runtime asset table
#                     consumed by native/embedded_assets.hpp.
#
# Invoked from CMakeLists.txt via:
#   cmake -DASSET_DIR=...
#         -DOUTPUT_RC=...
#         -DOUTPUT_CPP=...
#         -P GenerateViewerResources.cmake
#
# Entries are sorted by URL path so the runtime table is
# binary-searchable. The CSP-relevant content_type field is filled
# from a fixed extension -> MIME map (see mime_for_extension below).

if(NOT DEFINED ASSET_DIR OR NOT DEFINED OUTPUT_RC OR NOT DEFINED OUTPUT_CPP)
    message(FATAL_ERROR
        "GenerateViewerResources.cmake requires "
        "ASSET_DIR, OUTPUT_RC, OUTPUT_CPP.")
endif()

if(NOT EXISTS "${ASSET_DIR}")
    message(FATAL_ERROR
        "ASSET_DIR (${ASSET_DIR}) does not exist - "
        "did you run `npm run build` in viewer/?")
endif()

file(GLOB_RECURSE ALL_FILES RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*")

# Exclude things we don't want in the DLL.
list(FILTER ALL_FILES EXCLUDE REGEX "(^|/)\\.vite/")
list(FILTER ALL_FILES EXCLUDE REGEX "\\.map$")
list(FILTER ALL_FILES EXCLUDE REGEX "\\.stamp$")    # build-stamp sentinels
list(FILTER ALL_FILES EXCLUDE REGEX "(^|/)\\.")     # any other dotfile

if(NOT ALL_FILES)
    message(FATAL_ERROR
        "ASSET_DIR (${ASSET_DIR}) has no embeddable files - "
        "did you run `npm run build` in viewer/?")
endif()

# Sort so URL-path order in the generated table is deterministic,
# enabling binary-search lookup at runtime.
list(SORT ALL_FILES)

# Extension -> MIME, queried at generate-time. Unknown extension is
# a warning so we notice if Vite ever emits a new format.
function(mime_for_extension EXT OUT)
    string(TOLOWER "${EXT}" EXT)
    if(EXT STREQUAL "html" OR EXT STREQUAL "htm")
        set(${OUT} "text/html; charset=utf-8" PARENT_SCOPE)
    elseif(EXT STREQUAL "js" OR EXT STREQUAL "mjs")
        set(${OUT} "text/javascript; charset=utf-8" PARENT_SCOPE)
    elseif(EXT STREQUAL "css")
        set(${OUT} "text/css; charset=utf-8" PARENT_SCOPE)
    elseif(EXT STREQUAL "json" OR EXT STREQUAL "map")
        set(${OUT} "application/json; charset=utf-8" PARENT_SCOPE)
    elseif(EXT STREQUAL "svg")
        set(${OUT} "image/svg+xml" PARENT_SCOPE)
    elseif(EXT STREQUAL "png")
        set(${OUT} "image/png" PARENT_SCOPE)
    elseif(EXT STREQUAL "jpg" OR EXT STREQUAL "jpeg")
        set(${OUT} "image/jpeg" PARENT_SCOPE)
    elseif(EXT STREQUAL "webp")
        set(${OUT} "image/webp" PARENT_SCOPE)
    elseif(EXT STREQUAL "gif")
        set(${OUT} "image/gif" PARENT_SCOPE)
    elseif(EXT STREQUAL "woff")
        set(${OUT} "font/woff" PARENT_SCOPE)
    elseif(EXT STREQUAL "woff2")
        set(${OUT} "font/woff2" PARENT_SCOPE)
    elseif(EXT STREQUAL "wasm")
        set(${OUT} "application/wasm" PARENT_SCOPE)
    elseif(EXT STREQUAL "txt")
        set(${OUT} "text/plain; charset=utf-8" PARENT_SCOPE)
    else()
        message(WARNING
            "GenerateViewerResources: unknown extension '${EXT}'; "
            "defaulting to application/octet-stream.")
        set(${OUT} "application/octet-stream" PARENT_SCOPE)
    endif()
endfunction()

set(NEXT_ID 2000)
set(RC_LINES "")
set(CPP_ENTRIES "")

foreach(FILE_REL IN LISTS ALL_FILES)
    set(URL_PATH "/${FILE_REL}")
    set(ABS_PATH "${ASSET_DIR}/${FILE_REL}")
    # Backslashes confuse the resource compiler; cmake gives us
    # forward slashes on Windows anyway, but be explicit.
    string(REPLACE "\\" "/" ABS_PATH "${ABS_PATH}")

    get_filename_component(EXT "${FILE_REL}" LAST_EXT)
    if(EXT)
        string(SUBSTRING "${EXT}" 1 -1 EXT)
    endif()
    mime_for_extension("${EXT}" MIME)

    string(APPEND RC_LINES
        "${NEXT_ID} RCDATA \"${ABS_PATH}\"\n")
    string(APPEND CPP_ENTRIES
        "    { L\"${URL_PATH}\", ${NEXT_ID}, L\"${MIME}\" },\n")

    math(EXPR NEXT_ID "${NEXT_ID} + 1")
endforeach()

file(WRITE "${OUTPUT_RC}" "${RC_LINES}")

file(WRITE "${OUTPUT_CPP}"
"// Auto-generated by GenerateViewerResources.cmake. DO NOT EDIT.
// Source: ${ASSET_DIR}

#include \"native/embedded_assets.hpp\"

namespace mdview::assets {

static constexpr EmbeddedAsset kAssets[] = {
${CPP_ENTRIES}};

std::span<const EmbeddedAsset> table() noexcept {
    return kAssets;
}

}  // namespace mdview::assets
")
